### ISSUE TITLE
Review and remove unnecessary parameters

### ISSUE THREAD

**Issue by irvingpop** [chef-customers/aws_native_chef_server#24]
Boy does this template have a lot of parameters!  We could make it less confusing to new users if we eliminate some of the most unneeded ones.

In my own personal order:

1.  `SSHSecurityGroup` -  this allows you to specify an SG that can SSH to the frontends.  often the default SG for ChefServerSubnets would cover that.
2.  `DBSubnetGroupArn` - we identified one rare case a while ago where a customer couldn't create DB subnet groups.   pretty sure that no sane AWS setup actually operates that way, does it?
3.  LoadBalancerSubnets - how many people actually need to put LBs on different subnets than their FEs?

looking for feedback from @itmustbejj @lcc2207 @griffint61

**Comment by lcc2207** [comment]
@irvingpop 
1) I agree a default SG for Chef server would be fine
2) we have not touched this in our install
3) this is unneeded in our env as we put instances and ELB on the same subnet

**Comment by griffint61** [comment]
@irvingpop 

1. We use the SSH security group option. Our security folks require us to install intrusion-detection s/w on all of our EC2 instances, and that requires certain ports to be open. We piggy-back on a custom SSH security group to make that happen. If there were some way to specify another security group in addition to the stock SSH group, that would meet our needs.
2. We're not using that one. Wouldn't miss it.
3. I don't think we'd miss it. The generic use case for such a split is when you want to put the LBs in public subnets with the FEs in private subnets, which is standard practice for Internet-facing services. But unless you have customers with a desire for an Internet-facing Chef Server, I'd drop that one.

**Comment by lcc2207** [comment]
@irvingpop @griffint61 what are you thoughts on removing the URL input options for Chef server/ Manage and Push, as you have to manually replace these on existing runs on upgrades of existing installs.

**Comment by griffint61** [comment]
@lcc2207 @irvingpop We are currently using the "ChefServerPackage" setting, but it's one-off thing. We probably won't need it in the future. (For reasons of migrating from the old DRDB-HA stack to AWS-Native stack, we had to pin to 12.15.8 instead of using the current default 12.16.9.) That said, I'm not sure you could get rid of these. People like to have control of the version. Additionally, they might have reason to download the RPMs from some in-house repository.

**Comment by irvingpop** [comment]
we could hypothetically use the [cfn-init package resources](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-init.html#aws-resource-init-packages) to add the packages.chef.io yum repo and then install the packages and still specify versions.

The only reason I'm against that is due to customer scenarios we've encountered where they want to deploy chef servers with no outbound internet access at all,  typically loading the packages and even the main.sh script on an S3 bucket.

**Comment by irvingpop** [comment]
okay so it sounds like we have consensus on removing items 2 and 3

**Comment by itmustbejj** [comment]
👍  on removing items 2 and 3.

**Comment by irvingpop** [comment]
Thanks for the feedback everyone.   Those changes have been made in this PR:  https://github.com/chef-customers/aws_native_chef_server/pull/25   please follow along there!
