### ISSUE TITLE
AWS::ElasticLoadBalancingV2::LoadBalancer Name

### ISSUE THREAD

**Issue by SonyDavid** [chef-customers/aws_native_chef_server#26]
The Name value isn't a required field so I recommend removing it so that if LB needs updating you can. But putting a name you get:

UPDATE_FAILED | AWS::ElasticLoadBalancingV2::LoadBalancer | ChefALB | CloudFormation cannot update a stack when a custom-named resource requires replacing. Rename Chef-lb and update the stack again.

**Comment by irvingpop** [comment]
Thanks for bringing that to our @SonyDavid, this is a bit of a pickle we're in!   

Looking at the docs, I see how making a fundamental change to the load balancer  will result in Replacement of the resource (likely the Scheme, am I right?).    Unfortunately another value that requires replacement is `Name` itself, which is a problem for all the production deployments already in existence.

If it is only Scheme, would it be fair to say that a cluster mistakenly deployed with the wrong scheme can be safely re-deployed (destroy & re-create the stack) without too much heart-ache?

**Comment by SonyDavid** [comment]
The situation I encounter this in was updating a subnet of the ELB. I was adding an additional subnet and the system broke. What I had to do to fix it was rename the resource and all the references, redeploy. Then change them back without the name entry. 

So I'm not sure if it's best to fix it or not?

**Comment by irvingpop** [comment]
That's weird - [the cloudformation docs](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html) specifically say that changing `Subnets` for an ALB requires no interruption.  If that's not the case we should take it up with AWS.

**Comment by irvingpop** [comment]
v4 of this template omits the name field for the ALBs, so this should be fixed now!
