### ISSUE TITLE
WaitCondition timed out.

### ISSUE THREAD

**Issue by jdpc02** [chef-customers/aws_native_chef_server#28]
The WaitCondition resource seems to just time out ("WaitCondition timed out. Received 0 conditions when expecting 1"). Whenever I try to kick off a build, I keep getting tripped up by this resource. Any suggestions on troubleshooting the issue?

**Comment by irvingpop** [comment]
Hey @gitdave225 that means that the Bootstrap Frontend isn't completing its configuration run.  You'll want to look at the /var/log/cloud-init* and /var/log/cfn-init* logfiles to see why.

If that machine is being terminated too quickly for you to see, try commenting out this line: https://github.com/chef-customers/aws_native_chef_server/blob/master/backendless_chef.yaml#L593

**Comment by jdpc02** [comment]
Thanks. I think I found my problem. Basically, it is failing at the initctl start aws-signing-proxy part. We use a custom CENTOS AMI and of course initctl is not part of the build.

I am a bit of a newbie about this but what is the reason why we are running aws-signing-proxy this way? Can't I just call it explicitly? Any other ways of doing this using systemctl instead?

            01_start_es_proxy:
                  command: initctl start aws-signing-proxy

**Comment by irvingpop** [comment]
hey @gitdave225 unfortunately the template as it currently stands only supports Amazon Linux.   The primary issues are how we expect the AWS tools installed (you've likely solved that already) and the assumption that the init system is Upstart (RHEL7-alikes all use systemd).

If you really want this to work on CentOS, you'll need to modify the template to write out a systemd service file and use `systemctl` instead of `initctl`.    

The good news is that Amazon Linux 2 was announced recently and also switches to systemd, so we'll likely need to solve this soon anyway 😄

**Comment by jdpc02** [comment]
That's what I figured. I think we got a good service file to work though to be honest I am unsure if I should start it where the aws-signing-proxy.yml file is located.

Here is my attempt at it:
[Unit]
Description=AWS-Signing-Proxy Service
After=network.target

[Service]
Type=simple
Restart=on-failure
RestartSec=10
startLimitIntervalSec=60
ExecStart=/usr/local/bin/aws-signing-proxy
ExecReload=/bin/kill -HUP $MAINPID
StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=AWS-Signing-Proxy

[Install]
WantedBy=multi-user.target

**Comment by irvingpop** [comment]
take a look here: https://github.com/chef-customers/aws_native_chef_server/blob/master/backendless_chef.yaml#L679

**Comment by jdpc02** [comment]
Yep found that section and updated my own copy. It works when I updated the entry.
Now I am getting stuck with the main.sh file. For some reason it is not running properly or causing a failure during the build. I will try to manually run the file and see if I can get it to work.

**Comment by irvingpop** [comment]
good luck @gitdave225 !   If you want to talk in a more interactive fashion next week,  many of us are in the Chef Community slack ( http://community-slack.chef.io/ ) in the `#chef-server-ha` channel

**Comment by jdpc02** [comment]
Will do
