### ISSUE TITLE
Failing ASGs Result in Massive Downloads from packages.chef.io

### ISSUE THREAD

**Issue by sean-horn** [chef-customers/aws_native_chef_server#33]
ASGs, bootstrap or otherwise should fail after a few tries to come up normally.

**Comment by irvingpop** [comment]
Howdy @sean-horn do you have any ideas on how to implement that?   

Is "Massive" really fair, given a cycle time of a few minutes  (Let's call it 15 re-launches per hour).

**Comment by trickyearlobe** [comment]
Yup, its a real problem. I used this for a customer last week and it resulted in them getting blocked at packages.chef.io after the 3rd failed deployment attempt.

**Comment by irvingpop** [comment]
I'm still completely open to practical suggestions and fixes 😉

**Comment by irvingpop** [comment]
This is somewhat fixed in the v4 template released this week,  as I commented out the line that caused all the pain:
https://github.com/chef-customers/aws_native_chef_server/blob/master/chef_server_ha.yaml#L431-L432
