### ISSUE TITLE
Implement Chef Package Repo Mirror

### ISSUE THREAD

**Issue by sean-horn** [chef-customers/aws_native_chef_server#34]
This serves multiple purposes

* Protect packages.chef.io from undue load

* Provide a local packages.chef.io package repo mirror for each AWS Native install for speed

* Provide a general package repo for regular client bootstraps and other product installations

https://github.com/chef/mixlib-install seems like a good candidate for the purpose of building such a repo, as it can handle all package types, including windows as well as generate usable install.sh/install.ps1

The build might go something like

1. Get all the packages, potentially filtering on a specific OS/architecture
2. Build repos and mirroring for the selected OS types
3. Bootstrap some things locally!

**Comment by irvingpop** [comment]
Are you saying that the package repo mirror should be launched as part of this cloudformation stack?   Or that we should be instructing more customers to build package repo mirrors?

**Comment by irvingpop** [comment]
Had an idea on a cheapo way to implement some basic caching.   we could implement a simple script that does this:

1. input the source package URL.  
2. If the source URL =~ "packages.chef.io", then trigger mirroring function
3.  Test for existence of package at ${S3_BUCKET}/packagename.rpm 
4.   if doesn't exist, retrieve from packages.chef.io and upload to $S3_BUCKET
5.   if exists, retrieve directly from $S3_BUCKET  (probably checksum to ensure you didn't get a corrupt or incomplete file)

thoughts?  anyone want to take a crack at this?

**Comment by rwc** [comment]
@irvingpop - I'm likely going to break this out in a separate project as I've already written the bones and it'd be awesome for customers to have as an individual artifact to use outside of `aws_native_chef_server.` We can look at optimizing the way we do component upgrades in this project to use a private repo mirror.

**Comment by trickyearlobe** [comment]
To save re-inventing the wheel, couldn't we just spin up a Nexus instance and configure it to proxy the Chef YUM repo? Nexus 3.12 and above can use S3 as the blob store.

**Comment by irvingpop** [comment]
I think that's the intention @trickyearlobe , but the package URLs are simply URLs so you can point them wherever.

**Comment by irvingpop** [comment]
This is somewhat fixed in the v4 template released this week,  as I commented out the line that caused all the pain:
https://github.com/chef-customers/aws_native_chef_server/blob/master/chef_server_ha.yaml#L431-L432

**Comment by irvingpop** [comment]
This is fixed properly by PR #50
