### ISSUE TITLE
Wrong FQDN in `api_fqdn`

### ISSUE THREAD

**Issue by trickyearlobe** [chef-customers/aws_native_chef_server#38]
The `api_fqdn` in the `chef-server.rb` gets set to the FQDN of the load balancer instead of the FQDN being based off the DNS entry.

The result is a mostly working Chef server, but there are a couple of issues:-

* Confirmation eMails for user self-registrations contain a clickable link with the wrong FQDN resulting in SSL problems in the browser (cert doesn't match requested URL)
* Chef starter kits contain the wrong FQDN in the `knife.rb` which also result in SSL problems.

**Comment by irvingpop** [comment]
great catch @trickyearlobe, I'm surprised nobody has complained about this yet 😄 

That's a relatively easy fix to make, do you have some cycles to submit a PR?

**Comment by irvingpop** [comment]
This is fixed now in v4 of the template, released this week
