### ISSUE TITLE
Bookshelf SignatureDoesNotMatch Errors With Multiple Backends

### ISSUE THREAD

**Issue by skarlupka** [chef-customers/aws_native_chef_server#40]
When more than one chef server is running behind an ELB, Bookshelf complains of SignatureDoesNotMatch when clients are downloading cookbooks.  This happens when in "sql" mode.  The fix is to ensure 

bookshelf['access_key_id']
bookshelf['secret_access_key']

are the same on every backend server during bootstrap.  If these settings are not set a random string is generated so each backend is expecting a different keypair.

chef-server-ctl set-secret bookshelf access_key_id
and 
chef-server-ctl set-secret bookshelf secret_access_key 

need to be run at bootstrap time.  The values could be stored in aws ssm for easy access.

**Comment by irvingpop** [comment]
Interesting, I've never seen this issue across probably hundreds of AWS chef server deployments.  Could you please provide more information?  (all package versions involved, did you make any modifications to this template, etc)

**Comment by skarlupka** [comment]
@irvingpop Thank you for the quick reply.  You can close this ticket.  I realized that we were not keeping /etc/opscode in sync across all of the chef servers.  Doing this will fix all of our secret mismatch issues.
