### ISSUE TITLE
Attribute: PublicIp was not found for resource: instance-ID

### ISSUE THREAD

**Issue by zerolaser** [chef-customers/aws_native_chef_server#46]
Ran into the following issue while running the latest 4.0.0 stack.
Set the parameters  `AssociatePublicIpAddress` to  false and `LoadBalancerScheme` to internal

```
Embedded stack chef-AutomateStack was not successfully created: 
Attribute: PublicIp was not found for resource: i-XXXXXXX
```

Had the same issue when the parameters are set to true and internet-facing
Note: our subnets used, doesn't allow the public ip address.

**Comment by irvingpop** [comment]
this should be fixed by PR #50
