### ISSUE TITLE
Elasticsearch, Cloudformation and ZoneAwareness, the struggle is real

### ISSUE THREAD

**Issue by irvingpop** [chef-customers/aws_native_chef_server#49]
AWS [recently added 3-AZ zone awareness to Elasticsearch](https://aws.amazon.com/blogs/database/increase-availability-for-amazon-elasticsearch-service-by-deploying-in-three-availability-zones-2/).   

This is awesome because previously `ZoneAwarenessEnabled`  forced you into some bad decisions:
1.  Run with this value `false` and you only get good availability at the ES software level, because that requires 3 instances, but they are all in a single zone
    - This is what we do today, and if AWS loses an AZ then you'll have a very bad time
2. Run with this value `true` and you're forced to specify an even number of ES instances 
    -  either 2 (which gives you poor availability) 
    - or 4 which is super expensive and overkill for us

Amazon provides a good document on the availability trade-offs: https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-managedomains.html#es-managedomains-multiaz  - particularly this table:

<img width="824" alt="Screen Shot 2019-03-08 at 1 59 37 PM" src="https://user-images.githubusercontent.com/1616328/54058366-7c781100-41aa-11e9-91e2-05b381eb1886.png">

Unfortunately, Cloudformation doesn't yet support 3-AZ awareness, so we are forced to wait until it does 😞- [keep an eye on this page](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-elasticsearchclusterconfig.html)

**Comment by irvingpop** [comment]
Once Cloudformation adds support for this, we need to think about the UX for aws_native users.  In no particular order:

1. Ensuring (or better documenting) that at least 3 subnets must be passed in
2. Probably hard-coding `ChefElasticSearchShardCount` to 3,  to prevent people from footgunning themselves.   An alternative is that we could set AllowedValues to only be multiples of 3 (3,6,9)
3. What happens if someone applies these changes to a live cluster?   
  - Need to test so we know if the whole cluster is replaced (an outage event requiring manual intervention) or if it does the right thing behind the scenes

**Comment by irvingpop** [comment]
FWIW, Terraform is also still working on this feature.  This will be an interesting test to see who can ship it faster 😄 
https://github.com/terraform-providers/terraform-provider-aws/pull/8144

**Comment by irvingpop** [comment]
Adding another point of tracking, there's been an open request for this in the AWS forums since March.  Please add your voices here!  https://forums.aws.amazon.com/thread.jspa?messageID=905336&#905336

**Comment by irvingpop** [comment]
An update:  the AWS Cloudformation team has opened up [their roadmap to public viewing](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/projects/1).

As of today, the Cloudformation feature we need is in the "Coming Soon" column: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/8

**Comment by pdohertybcov** [comment]
It looks like the change has finally landed.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-zoneawarenessconfig.html
