### ISSUE TITLE
HealthCheckIntervalSeconds and UnhealthyThresholdCount need saner defaults

### ISSUE THREAD

**Issue by itmustbejj** [chef-customers/aws_native_chef_server#54]
The current default has failing health checks for 10 minutes before being flagged as unhealthy.
https://github.com/chef-customers/aws_native_chef_server/blob/master/chef_server_ha.yaml#L388-L389

**Comment by irvingpop** [comment]
what do you think about this @itmustbejj ?
https://github.com/chef-customers/aws_native_chef_server/pull/56/commits/3809492ecad5803007763273cb44a2e439cac12f
