### ISSUE TITLE
Current version of Chef Infra Server in images has ldap ssl bug

### ISSUE THREAD

**Issue by sam1el** [chef-customers/aws_native_chef_server#55]
After testing with a customer this week, we found that the images are using Chef server core 12.19.31. This causes the server not to allow ldap over SSL which was a requirement for the customer unfortunately. Downgrading to 12.18.14 fixed the issue for now.

**Comment by irvingpop** [comment]
Thanks for the feedback @sam1el - do you know if rolling forward to Chef Server 13.0.x releases helps at all?

**Comment by irvingpop** [comment]
For reference, this is the chef-server issue: https://github.com/chef/chef-server/issues/1642
