### ISSUE TITLE
Are the build scripts for the pre-baked AMIs available?

### ISSUE THREAD

**Issue by gdavison** [chef-customers/aws_native_chef_server#58]
Our security policies only allow the deployment of AMIs that we've built ourselves. Are the build scripts for the AMIs referenced in `main.yaml` available anywhere? We'd like to be able to leverage this repo, but the AMI list is a problem.

**Comment by irvingpop** [comment]
hi @gdavison absolutely, the build scripts are all open:  https://github.com/irvingpop/packer-chef-highperf-centos7-ami/blob/master/packer-marketplace.json#L69

**Comment by irvingpop** [comment]
hey @gdavison I'm closing this issue out as the question appears to be answered.  Please reopen or create a new issue if you need anything else
