### ISSUE TITLE
Add parameter to set ELB security policy

### ISSUE THREAD

**Issue by jeffj254** [chef-customers/aws_native_chef_server#63]
Currently the templates do not specify an ELB security policy which means they are set with the AWS default of `ELBSecurityPolicy-2016-08`.  This security policy allows TLS 1, 1.1, and 1.2.  Our corporate standards require us to limit connections to only TLS 1.2.

It would be helpful to add another parameter to the templates to allow a different security policy to be specified than the default, if desired.

**Comment by irvingpop** [comment]
doh, this is a no-brainer and needs to be fixed ASAP :)
