### ISSUE TITLE
Current method of installing pip is not compatible with VPCs where internet access is filtered through Squid

### ISSUE THREAD

**Issue by jeffj254** [chef-customers/aws_native_chef_server#66]
Our corporate VPCs use Squid gateways to provide filtered internet with a URL whitelist to our VPC private subnets.  While I have been able to whitelist most endpoints required by the templates, I have run into a problem with the pip install process.

Currently pip is installed during instance startup by the `awslogs-agent-setup.py` script.  This script uses `easy_install` from the python setuptools package to install pip.  Unfortunately it seems easy_install does not format some of it's http requests correctly and essentially sends the requests directly to an IP instead of to a specific URL.

This causes our Squid gateways to block the request since there is no URL to check against the whitelist.  Easy_install then fails to install Squid and the stack creation as a whole fails due to the instance not finishing cfn-init successfully.

I have been able to work around this problem by installing pip through yum before the awslogs-agent-setup.py script executes by adding a `yum install -y python-pip` line before the awslogs script runs, so pip is already there and the easy_install command is skipped.  This is a bit of a hacky workaround though, and not something I feel should be contributed back.

Is this something I should just take as a required customization for our version of the templates or is there another method that could be used to install pip that is friendly to our URL whitelisting?

**Comment by irvingpop** [comment]
Thanks for catching this!   My goal is for the machines to not reach out during provisioning time at all, so this needs to be fixed in the packer build process, probably here: https://github.com/irvingpop/packer-chef-highperf-centos-ami/blob/master/scripts/marketplace_dl.sh

**Comment by jeffj254** [comment]
Pull request created to update marketplace_dl.sh: https://github.com/irvingpop/packer-chef-highperf-centos-ami/pull/10

**Comment by jeffj254** [comment]
Closing this since it was resolved with the ami update in 5.0.5
