### ISSUE TITLE
Bootstrap server looping after stack creation

### ISSUE THREAD

**Issue by Tensibai** [chef-customers/aws_native_chef_server#69]
https://github.com/chef-customers/aws_native_chef_server/blob/bce23346b8fee3461c4872d0fa90992307bd0a7f/chef_server_ha.yaml#L451

The command here will fail if the stack is created, thus triggering the trap defined a bit above. 

In case someone terminate the bootstrap instance by mistake or it goes unresponsive you're loosing the bootstrap/pushjob instance as it is reported unhealthy because of this command failure.

I've worked around it with a ` || echo "Ok, nevermind"` to avoid that. 
A better solution would be to test the stack state before trying to signal it.

**Comment by irvingpop** [comment]
weird!  I wonder if the behavior changed, because I've never experienced that command exit > 0 when the stack is already created (for example during ASG actions).

Just for my own edification, could you please run that command and show me the output on an already created stack?

**Comment by Tensibai** [comment]
When running the command on an actual instance I get this:

```
# /usr/local/bin/cfn-signal -e 0 -r "Server setup complete" 'https://cloudformation-waitcondition-eu-west-3.s3.eu-west-3.amazonaws.com/arn%3Aaws%3Acloudformation%3Aeu-west-3%3A370779979152%3Astack/chef-server/exxxxxxx2/WaitHandle?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200116T104235Z&X-Amz-SignedHeaders=host&X-Amz-Expires=86399&X-Amz-Credential=Axxxxxxxxxxx%2Feu-west-3%2Fs3%2Faws4_request&X-Amz-Signature=exxxxxxxxxxxxxe'; echo "return code: $?"
Error signaling CloudFormation: [Errno 403] HTTP Error 403 : <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Request has expired</Message><X-Amz-Expires>86399</X-Amz-Expires><Expires>2020-01-17T10:42:34Z</Expires><ServerTime>2020-01-23T08:48:56Z</ServerTime><RequestId>4xxxxxxxx8</RequestId><HostId>+1gFxxxxxxxxxxxxxxxxxxxxxxxxxxx84=</HostId></Error>
return code: 1
```

I've no idea why you never experienced it :D Maybe that's a version problem ? I'm using the latest version from  https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz

**Comment by irvingpop** [comment]
ok, I agree this needs to be fixed.  Could you PR it please?
