### ISSUE TITLE
S3 Bucket Public Access Error for v5.1.1 CF Templates

### ISSUE THREAD

**Issue by ChefAustin** [chef-customers/aws_native_chef_server#79]
When trying to access any of the v5.1.1 CF templates [1] the S3 bucket seems to return the `AccessDenied` error.

Oddly enough, v5.0.3 and v5.0.1 CF templates are able to be pulled-down without issue. 🤷 

[1] i.e. =>
https://s3.amazonaws.com/aws-native-chef-server/5.1.1/marketplace.yaml
https://s3.amazonaws.com/aws-native-chef-server/5.1.1/main.yaml
https://s3.amazonaws.com/aws-native-chef-server/5.1.1/chef_server_ha.yaml

**Comment by StylusEaterChef** [comment]
Confirmed this is an issue. Works all the way up to v5.1.0. Working on correcting it.

**Comment by StylusEaterChef** [comment]
@ChefAustin this should now be fixed. Thanks @gsreynolds!

**Comment by gsreynolds** [comment]
The bucket default ACL was set to public read, but the files in 5.1.1 had object level ACLs. Have resolved this now.
